config/routes.rb
Rails.application.routes.draw do
  get 'pages/profile'
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#index'
  resources :users, only: [:index, :new, :create, :edit, :update]
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :admin, only: [:edit, :update, :destroy]
  resources :packages, only: [:index, :create, :destroy, :edit, :new, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/package.rb
class Package < ApplicationRecord
  validates :sender, presence: true
  validates :recipient, presence: true
  validates :content, presence: true
  validates :weight, presence: true

  def self.update_with_lock(id, new_attributes)
    record = find(id)

    # Acquire a lock on the record
    record.lock!
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 12 }, if: :password_required?
  validates :email, presence: true
  validates :address, presence: true
  validates :telnr, presence: true

  def password_required?
    new_record? || !password.nil? || !password_confirmation.nil?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin, only: [:edit, :update, :destroy]

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
  
    if @user.update(user_params)
      flash[:alert] = "User updated successfully"
      redirect_to users_index_path
    else
      flash[:alert] = "User not updated"
      render :edit, status: :unprocessable_entity
    end
  end  

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, alert: 'User deleted'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email, :address, :telnr, :role)
  end

  def require_admin
    unless current_user&.admin?
      redirect_to root_path, alert: "403 Forbidden"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages = Package.all
  end

  def new
    @package = Package.new
  end

  def create
    @package = Package.new(package_params)

    if @package.save
      flash[:alert] = "Package created successfully"
      redirect_to packages_path
    else
      console
      flash[:alert] = "Package not created"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @package = Package.find(params[:id])
  end
  
  def update
    @package = Package.find(params[:id])
  
    Package.transaction do
      if @package.update(package_params)
        flash[:alert] = "Package updated successfully"
        redirect_to packages_path
      else
        flash[:alert] = "Package not updated"
        render :edit, status: :unprocessable_entity
      end
    end
  end  

  def destroy
    @package = Package.find(params[:id])
    @package.destroy
    redirect_to packages_path, alert: 'Package deleted'
  end

  private

  def package_params
    params.require(:package).permit(:sender, :recipient, :content, :weight, :destination)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def profile
    if current_user.blank?
      render plain: '401 Unauthorized', status: :unauthorized
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def index
    binding.break
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: :index

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.user!
      flash[:alert] = "User created successfully"
      redirect_to users_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:alert] = "Profile updated successfully"
      redirect_to pages_profile_path
    else
      flash[:alert] = "Profile not updated"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email, :address, :telnr, :role)
  end

  def require_admin
    unless current_user&.admin?
      redirect_to root_path, alert: "403 Forbidden"
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/package_helper.rb
module PackageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

app/views/admin/edit.html.erb
<h1>Edit User</h1>
<%= form_with(model: @user, url: admin_path(@user), method: :patch) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :telnr %>
    <%= f.text_field :telnr %>
  </div>

  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M223</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/package/create.html.erb
<h1>Package#create</h1>
<p>Find me in app/views/package/create.html.erb</p>

app/views/package/destroy.html.erb
<h1>Package#destroy</h1>
<p>Find me in app/views/package/destroy.html.erb</p>

app/views/pages/index.html.erb
<% if current_user %>
  <h1>Welcome, <%= current_user.username %></h1>
  <%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete } %><br>
<% else %>
  <h1>This is the index page</h1>
  <%= link_to 'Login', new_user_session_path %><br>
<% end %>
<br>
<%= link_to 'Packages', packages_path %>
<br>
<br>
<%= link_to 'Profile', '/pages/profile' %>
<br>
<%= link_to 'New User', new_user_path %>
<br>
<%= link_to 'Users', '/users/index' %>

app/views/pages/profile.html.erb
<h1>Profile</h1>

<table>
  <thead>
    <tr>
      <th>username</th>
      <th>email</th>
      <th>address</th>
      <th>telephone number</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @current_user.username %></td>
      <td><%= @current_user.email %></td>
      <td><%= @current_user.address %></td>
      <td><%= @current_user.telnr %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit Profile', '/users/edit' %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>UserSessions#new</h1>
<h1>Login page</h1>
<%= form_with model: @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :telnr %>
    <%= f.text_field :telnr %>
  </div>

  <div class="actions">
    <%= f.submit "Update Profile" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>username</th>
      <th>email</th>
      <th>address</th>
      <th>telephone number</th>
      <th>actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.telnr %></td>
        <td>
          <%= link_to "Edit", edit_admin_path(user) %>
        </td>
        <td>
          <%= link_to "Delete", admin_path(user), data: { turbo_confirm: "Really delete this user?", turbo_method: :delete} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :telnr %><br>
    <%= f.text_field :telnr %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>